language: node_js
sudo: false
node_js:
  - "5"
env:
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=webpack FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=webpack FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=webpack FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=inject FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=inject FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=react FOUNTAIN_MODULES=inject FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=inject FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=inject FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=angular1 FOUNTAIN_MODULES=inject FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=webpack FOUNTAIN_JS=typescript
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=babel
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=js
  - FOUNTAIN_FRAMEWORK=angular2 FOUNTAIN_MODULES=systemjs FOUNTAIN_JS=typescript

notifications:
  email: false

git:
  submodules: false

cache:
  timeout: 600
  directories:
    - node_modules
    - fountain-generator/node_modules
    - generator-fountain-angular1/node_modules
    - generator-fountain-angular2/node_modules
    - generator-fountain-browsersync/node_modules
    - generator-fountain-eslint/node_modules
    - generator-fountain-gulp/node_modules
    - generator-fountain-inject/node_modules
    - generator-fountain-karma/node_modules
    - generator-fountain-react/node_modules
    - generator-fountain-systemjs/node_modules
    - generator-fountain-tslint/node_modules
    - generator-fountain-webapp/node_modules
    - generator-fountain-webpack/node_modules
    - test/deps

addons:
   sauce_connect:
     username: "Swiip"
     access_key:
       secure: "xOc4vSbmwnufZY8MY/4pCzZX+6smPvgG6wHptArP1KIeBMpk6MG+LL8a5w23rVpNJzMO1iIRFDDZ5sAkrbvsXOKxZBkF123mG0JPvpYNhCQHxBgnqLvFTXeWoTb1G1dhhy1NklO4Y58ndLroiQ/ZkyPTFLiMv6uFU8GY7WeP3dw6VTCkXToGUgDNiW8bitGaiadVhVa3XzK/lNs9o6dAa6kl+bZ/UNCtrFFUmPFkcsY+99f37RzwRuzYWXEvguPY2N5zmuiohFL/XSlu73LeuF5UWxGHUtKKHiyt4VmNZCp2b3oL8EqtyBKFvAZJI5m9jfMgZ5SWgo+wBGZ/5N6nvDm3QsKoSQ6uJ0v0mEweysgh2pQ7abL5fvzF8mrDBZVoPyp/cOzTiUbLGRg02NsTxLtlKbG1rB8sO8qsyUcypFaEPzgCGIUlA/ibtkAOW7cVvsHiG5N3MFDOSHrwFFNEpyhIHdMj3VTU9tyPejWgIi25i6oUsscnAx/osrn2CgI5OieZlYn9M+HqEghMo/ikCNBQAwVr8c/VF6Z/lau1IPHOJg9//aMQwwrrnrgzzyH5vXXqvN9Yc/rxPi9ZPRGg0ImMTM4gNcZr/nVQRgqQ3nB/oqkEqZRmAK8HenZT8S6B1UCUhYx4zkLVsWXAuPVkPCL1K7jsYQHR3R7ygAYcgT4="

before_script:
  - node test/cache/remove-cache.js
  - rm -rf fountain-generator/ generator-fountain-*/
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - node test/cache/add-cache.js
  - node scripts/links.js
  - npm install -g mocha typings bower

script:
  - mocha test/travis-env

before_cache:
  - node scripts/unlinks.js
