language: node_js

node_js:
  - '4'
  - stable

env:
  global:
    - secure: lkTGpgQdeg5mBji8hg1ZpKO3eO4P0KNgy/VUY3o9WK9poKp+x8Hg72lwRsk2UYxeIUBzxJvSk0FFleeyKnEfH2o6nzvFqseUl+6WlOfFW2lVrDQD7gpT8uk73j6UNVT/oqh3mPO+Hw3c/AnFX7BtLaJJqjn684Twu/uX3wlP2T5dQVIdkHYWW4uxK1qvrGDHux3xDUrDMg+mO4GQKMqiPFlWUGcZHrZNwzMgkbFfhnPbV7W1BPtzPXWfOgVf++hy2wSEWJ3yxcGGC859VioBIgpxXZ6yYIzMto6HmgqL3OaH0jth5Ub5G3GOK1w5y0KmFT4p6wbFDhqm59hCXBxZ8cdD+YH6eEInvhwFbqaI2R1TFtJQCH6eAz3biGvq+vmkRSgwqmOI90F4gUha16xYvGIhDq27j1mVc/BrMtFAAOaa3R74HRHd0Y81FqcCPG2Og6qessns5nPJtSen6vvd9ZJVftRsMUhnOO8AovOZIodm0uP9iDNe3gwpWyXn0YUyXloXeZooXp+Fr6QhvzPcE70K2iwLkzudYhnC1e+s1eOVmPf40zB/vpCUAcuzf9CMxfq7fx1ALcAE8D+Fk2kW/kBZycBlT2KwK5VzpfeplbnuOASRjtlER/u/tDDzJoF/qgbSgQtO+kHWCZ1rImoYI9I4r2dOA8pk8CmUZW65BE8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: FountainJS/fountain

# Deactive fetch submodules by Travis. (e.g. before_script)
git:
  submodules: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# Enable cache for all node_modules
cache:
  timeout: 600
  directories:
    - node_modules
    - fountain-generator/node_modules
    - generator-fountain-angular1/node_modules
    - generator-fountain-angular2/node_modules
    - generator-fountain-browsersync/node_modules
    - generator-fountain-eslint/node_modules
    - generator-fountain-gulp/node_modules
    - generator-fountain-inject/node_modules
    - generator-fountain-karma/node_modules
    - generator-fountain-react/node_modules
    - generator-fountain-systemjs/node_modules
    - generator-fountain-tslint/node_modules
    - generator-fountain-webapp/node_modules
    - generator-fountain-webpack/node_modules
    - test/deps

addons:
  # Install Firefox
  firefox: "46.0"
  # Configure Sauce Labs fot e2e tests
  # sauce_connect:
  #   username: "zckrs"
  #   access_key:
  #     secure: "GRCFdTA5lYr51KaW4UAMV/oDxnm0CoPeYs1hZ2fynvv24X9KJhpukCNZNfYBVRg31gMUxGSzPOllFaHNBoExwb7/F7nndpG2FtBMlp8K22iGYDr8flRFJhd+5KJJRO4ed7z7hfHrbIwq3E2anoByh0NIFn5YO4FDwnf2ObFlFLAtyGppcTvr/UWpqzovFZLlAwU89YRZIFh7nzFUT2IU2BEWlR0TvVIhhNflpw7oScQDNtptZbGVKrJAMWT5VO15gTd97LKjyluHedZ6xWsN8TlOG2PSykI+7YYbz5Sat9l6PfBV2G4Nk5MOXivvW5mHZmXKcdGTfAoDGu9VSYFC+JdeW6DfOvS/ALagDaqmqKUyUY9eWRmt0UEMNoKhiCCe8agW2J3SiVaGVcobtCoB01nEU9iBmaVKAoZu9HbirSyEyc4j3DuQl8gAHEm/JOoTRFVIB/R7t9DPOjuFN5tHnGwO1tjkQtjCVuIz+feC3+EL819zuYCjzJ39MbQJZIiDtrsuBTkWj/SU5ECJgLyTM+qsI87XGVhtsD4UaWTCehvjs915yyLmGwm/D7dRHtno624e0zJo2Y4HHFOcKj1YXf2DaJI8NsApcyfOSWHg/O3yTURcNC/hKQ1avPDtaLpPYG3b4bpU4ubfyZCjzgjELEC7SpiL3AV17ieBCr2h3tM="

# Prepare build:
#   * Backup node_modules in ./temp/ provided by caches Travis
#   * Remove all fountain directories
#   * Replace protocol for git modules
#   * Fetch git modules
#   * Restore node_modules
#   * Generate all symlink across generators
#   * Install global packages needed
before_script:
  - node test/cache/backup-node_modules.js
  - rm -rf fountain-generator/ generator-fountain-*/
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - node test/cache/restore-node_modules.js
  - npm install --global npm@latest
  - npm run linkAll

# Run test
# script:
#   - npm test

# Avoid failed caching by Travis
before_cache:
  - npm run unlinkAll

after_success:
  - node ./scripts/bin/deploy
